---
name: "Container image tag"
description: "Bump a semantic version tag of a container image in Github CR"
inputs:
  image:
    description: "ghcr.io image path"
    required: true
    default: "timberhill/container-image-tag-action"
  minor-pattern:
    description: "Commit message pattern that indicates a minor version bump"
    required: true
    default: "#minor"
  major-pattern:
    description: "Commit message pattern that indicates a major version bump"
    required: true
    default: "#major"
outputs:
  new-tag:
    description: "The new image version"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.image }}
