---
name: "Container image tag"
description: "Bump a semantic version tag of a container image in Github CR"
inputs:
  image:
    description: "ghcr.io image path"
    required: true
    # default: "timberhill/container-image-tag-action"
  minor-pattern:
    description: "Commit message pattern that indicates a minor version bump"
    required: false
    default: "#minor"
  major-pattern:
    description: "Commit message pattern that indicates a major version bump"
    required: false
    default: "#major"
  include-v:
    description: "Whether or not to include 'v' prefix in the version"
    required: false
    default: "false"
  initial-tag:
    description: "Initial tag to create on first image push or first semver"
    required: false
    default: "0.1.0"
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
outputs:
  image-tag:
    description: "The new image version"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.image }}
    - ${{ inputs.minor-pattern }}
    - ${{ inputs.major-pattern }}
    - ${{ inputs.include-v }}
    - ${{ inputs.initial-tag }}
    - ${{ inputs.debug }}
