FROM node:alpine3.15

LABEL org.opencontainers.image.source=https://github.com/timberhill/container-image-tag-action

RUN apk update && apk add git curl jq
RUN export PATH=/usr/local/bin:$PATH && npm install semver -g

RUN adduser -u 1001 --disabled-password --no-create-home actionboi 
USER actionboi
