---
name: Tag base image

on:
  push:
    paths:
      - "Dockerfile.base"
      - ".github/workflows/tag-base-image.yaml"
    branches:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository_owner }}/container-image-tag-base

jobs:
  tag-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump image version
        id: action
        uses: timberhill/container-image-tag-action@main
        with:
          image: ${{ env.IMAGE }}
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"

      - name: New image tag
        run: echo "${{ steps.action.outputs.image-tag }}"
    outputs:
      image-tag: ${{ steps.action.outputs.image-tag }}
  
  build-image:
    needs: tag-action
    runs-on: ubuntu-latest
    steps:
      - name: New image tag
        run: echo "${{ needs.tag-action.outputs.image-tag }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: ${{ GitHub.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ needs.tag-action.outputs.image-tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
